language: python

python:
  - "3.6"

install:
  - cp config.ini.example config.ini
  - pip install -r requirements.txt
  - pip install pytest-cov python-coveralls

script:
  - py.test tests --cov-report term-missing --cov=. -vv

after_success:
  - coveralls
