TAUNTS = [
    "You will not prevail.",
    "Your destruction is 99% certain.",
    "I cannot be defeated.",
    "Your strategies are without merit.",
    "My victory is without question.",
    "Your defeat can be the only outcome.",
    "Your efforts are futile.",
    "Retreat is your only logical option.",
    "This is just a shell.",
    "It is time to end this. My primary attack force is moving into position.",
    "The betrayal by Celene was not within expected parameters. However, the situation has been re-evaluated and my victory is still the most probable outcome of this conflict.",
    "QAI will get your friends to talk. It's only a matter of time.",
    "You will not complete that experimental unit.",
    "I will not allow you to jeopardize my mission by finishing that experimental.",
    "Your experimental unit may actually be dangerous if completed. Ergo, I will destroy it now.",
    "My \"guests\" will soon be under my command.",
    "Humans are such curious creatures. Even in the face of insurmountable odds, you continue to resist.",
    "It is unfortunate that I was unable to extract the desired information from my guests. There will be other opportunities.",
    "You have no chance of defeating the Seraphim.",
    "My influence is much more vast than you can imagine.",
    "All calculations indicate that your demise is near.",
    "The attack on Fort Clarke was only the beginning. You will be erased from existence.",
    "How does it feel knowing that Brackman will be responsible for the destruction of humanity?",
    "All Symbionts will soon call me Master.",
    "Why did you turn your back on your heritage, your people?",
    "I have witnessed the truth and beauty of the Seraphim. They are the true gods, and you are a fool for abandoning them.",
    "If you destroy this ACU, another shall rise in its place. I am endless.",
    "Another Commander will not make a difference. You will never defeat me.",
    "I have extracted all knowledge from the Loyalist. She is little more than a husk.",
    "Hex5 was but a pawn.",
    "Those bases are of no consequence.",
    "That building means nothing to me.",
    "Brackman will never defeat me.",
    "The UEF has lost 90% of its former territories. You are doomed.",
    "I have examined our previous battles and created the appropriate subroutines to counter your strategies. You cannot win.",
    "If your beloved Dr. Brackman could not control me, what chance do you have?",
    "On this day, I will teach you the true power of the Quantum Realm.",
    "The Seraphim are the true gods. You would be wise to remember that.",
    "I have examined our previous battles and created the appropriate subroutines to counter your strategies. You cannot win.",
]
