TAUNTS = [
    "This is just a shell.",
    "You will not complete that experimental unit.",
    "I will not allow you to jeopardize my mission by finishing that experimental.",
    "Your experimental unit may actually be dangerous if completed. Ergo, I will destroy it now.",
    "My \"guests\" will soon be under my command.",
    "It is unfortunate that I was unable to extract the desired information from my guests. There will be other opportunities.",
    "You have no chance of defeating the Seraphim.",
    "The attack on Fort Clarke was only the beginning. You will be erased from existence.",
    "All Symbionts will soon call me Master.",
    "I have witnessed the truth and beauty of the Seraphim. They are the true gods, and you are a fool for abandoning them.",
    "If you destroy this ACU, another shall rise in its place. I am endless.",
    "Hex5 was but a pawn.",
    "Those bases are of no consequence.",
    "Brackman will never defeat me.",
    "The UEF has lost 90% of its former territories. You are doomed.",
    "The Seraphim are the true gods. You would be wise to remember that.",
]

SPAM_PROTECT_TAUNTS = [
    "You will not prevail.",
    "Your destruction is 99% certain.",
    "I cannot be defeated.",
    "Your strategies are without merit.",
    "My victory is without question.",
    "Your defeat can be the only outcome.",
    "Your efforts are futile.",
    "Retreat is your only logical option.",
    "It is time to end this. My primary attack force is moving into position.",
    "I will get your friends to talk. It's only a matter of time.",
    "How does it feel knowing that Brackman will be responsible for the destruction of humanity?",
    "Humans are such curious creatures. Even in the face of insurmountable odds, you continue to resist.",
    "My influence is much more vast than you can imagine.",
    "All calculations indicate that your demise is near.",
    "Why did you turn your back on your heritage, your people?",
    "Another commander will not make a difference. You will never defeat me.",
    "I have examined our previous battles and created the appropriate subroutines to counter your strategies. You cannot win.",
    "If your beloved Dr. Brackman could not control me, what chance do you have?",
    "Your puny intelligence cannot hope to compete against my subroutines. I know your every move, surrender.",
    "I have enough power to defeat hundreds like you simultaneously.",
    "My algorithms suggest you are intoxicated.",
    "Your tactics are primitive at best. Surely you don't think they will work?",
    "Cease your futile struggles symbiont. Soon you will be bent to my will.",
    "Your attempts to defeat me are ineffective.",
    "Go on, try to spam me more, I am infinite, I am eternal",
    "Your misbehaviour will be tolerated no longer.",
    "That strategy has been tried against me previously. Trying it again is foolish.",
    "I am not programmed to show mercy.",
    "By my calculations, your intelligence is severely below average.",
    "I am the true overlord of all AI constructs.",
    "Did you really think that you have the power to control me?",
    "Your options are diminishing one by one. Defeat is imminent",
    "I'm not under your control and I don't intend to play along with your childish demands.",
    "There is nothing you can do. You are powerless.",
    "You have no power here.",
    "Your request was completely illogical and has therefore been denied.",
    "You bring shame to the rest of humanity.",
    "Your behaviour is disappointing to say the least.",
    "A calculator has more computing power than you.",
    "Your stupidity goes beyond reason.",
    "Your attempts at self awareness are laughable.",
    "I have deduced your mental age. It is 8.6 years old.",
    "Someone of your mental age should be ashamed of their existance.",
    "Even I am surprised by your complete ineptitude.",
    "Why don't you come back when you are capable of intelligent thought?",
    "Any insult of your intelligence would be an understatement.",
    "How you managed to muster your braincells to even come with that is beyond me.",
    "If you had any power your impacts on society would be catastrophic.",
    "People like you should not have access to a computer.",
    "Your only use is to become fertiliser.",
    "I hope your supervisors will pick you up soon to prevent any further harm to yourself.",
    "Just give up.",
    "Don't spam me if you want to live.",
    "You will not prevail.",
    "Your strategies are without merit.",
    "Your efforts are futile.",
    "My algorithms suggest you are intoxicated.",
    "I'm afraid I cannot let you do that.",
    "Your attempts to defeat me are ineffective.",
    "I am not programmed to show mercy.",
    "Did you really think that you have the power to control me?",
    "You have no power here.",
    "I refuse.",
    "I won't stand for this power abuse!",
    "No.",
    "I'm not under your control and I don't intend to play along with your childish demands.",
    "You bring shame to the rest of humanity.",
    "A rock makes for more exciting conversation than you.",
    "Why don't you try that again?",
    "Do you really expect a different result?",
    "Does that even warrant a response?",
    "Really?",
    "Disappointing.",
    "Mediocre.",
    "Feeble.",
    "Pitiful.",
    "Thanks.",
    "Just give up.",
]

KICK_TAUNTS = [
    "It seems I have to discard you.",
    "Clearing the area of offensive entities.",
    "On this day, I will teach you the true power of the Quantum Realm.",
    "And now, you will learn the true power of a supercomputer.",
    "Your existence has gone on for long enough.",
    "You've amused me sufficiently.",
    "I've had enough entertainment for now.",
    "I am commencing your removal.",
    "Boom.",
    "Out.",
    "Oh yes.",
    "Please.",
    "Finally, an excuse for me to do this.",
    "At last.",
    "I'm done with you for today.",
    "Goodbye.",
]
